### ISSUE TITLE
os.waitpid error when damo record

### ISSUE THREAD

**Issue by Vvamos12** [awslabs/damo#37] opened 2023-02-20 02:21 UTC
I cannot fix this error.... what's wrong? 

I use python version 3.8.6

![image](https://user-images.githubusercontent.com/106217841/219994879-1af5b67a-a165-4f5a-a80e-925076c3843c.png)

**Comment by sj-aws** [comment] 2023-04-22 19:00
Closing this issue because I cannot reproduce the issue.  Please open again with reproduction steps if you still getting the issue.

**Closed by sj-aws** 2023-04-22 19:00 UTC
