### ISSUE TITLE
When i run damon record, some errors had happened

### ISSUE THREAD

**Issue by frankQAQ-wang** [awslabs/damo#24] opened 2021-08-24 03:47 UTC
root@debian:~/user-damon# ./damo/damo record 1
Traceback (most recent call last):
  File "./damo/damo", line 59, in <module>
    record.main(args)
  File "/root/user-damon/damo/record.py", line 140, in main
    new_attrs = _damon.cmd_args_to_attrs(args)
  File "/root/user-damon/damo/_damon.py", line 251, in cmd_args_to_attrs
    schemes = args.schemes
AttributeError: 'Namespace' object has no attribute 'schemes'

**Comment by frankQAQ-wang** [comment] 2021-08-24 03:58
commit 2773e71a69c6ca3f447e7903a77412a3ed92df90 make this mistake

**Comment by sj-aws** [comment] 2021-08-24 09:37
Thank you for the report!  I just confirmed fixed the issue with this commit: https://github.com/awslabs/damo/commit/d317c4a83ffed603bf01b0422353f57e12397a43

If the issue is not fixed on your machine, please open this again.

**Closed by sj-aws** 2021-08-24 09:37 UTC
