### ISSUE TITLE
Printing WSS at runtime (maybe with stat command)

### ISSUE THREAD

**Issue by honggyukim** [awslabs/damo#46] opened 2023-06-01 01:39 UTC
Hi SeongJae,

It was great to speak with you in the google meet. I asked a question about WSS printing at runtime and I remember you mentioned that the interface isn't fixed but maybe `stat` command can be used for that.

I actually don't get a clear idea how to use `stat` command for WSS printing so could you please give me some ideas how to use it?

I also feel that it's not easy to find the usage for each command somewhere in the help message or documents. It'd be really helpful if there is some example usages for each command.

Thanks.

**Comment by sj-aws** [comment] 2023-06-01 18:46
> how to use stat command for WSS printing

You could do, for example,
```
$ sudo ./damo start "./workload"
$ sudo ./damo stat regions --access_rate 5% max --size_only
```

> it's not easy to find the usage

Fully agreed.  It's mainly due to lack of my time, but also partly for some intent, as described in https://github.com/awslabs/damo#why-some-subcommands-are-not-documented-on-usagemd-file.

We're still officially supporting only record-report based workflow, namely `record`, `report`, `schemes`, and `monitor` commands.  We 're trying to extend it to start-stop workflow, and working on underlying features.  Documentation would be added at last, but it's still a long way to go.

**Comment by honggyukim** [comment] 2023-06-01 23:12
Thanks for the explanation. I've tried as you guided but the output doesn't look as expected.
```
$ sudo ./damo start "./masim/masim ./masim/configs/stairs.cfg"
(the shell is immediately returned)

$ sudo ./damo stat regions --access_rate 5% max --size_only
kdamond 0 ctx 0
0 B
```
I expected that the initial `damo stat` keeps running `masim` until it finishes but it just returns immediately without printing masim output.

Then `damo stat` output doesn't show something that looks like WSS info.

Could you please correct me if I did something wrong? My kernel version is `6.2.10`.

**Comment by sj-aws** [comment] 2023-06-03 18:03
Thank you for sharing the result.  And I confirmed it is reproducible on my test machine, too.

`damo start` is only for starting DAMON.  Returning immediately without waiting for `masim` is expected behavior.

`damo stat regions` output is what not expected.  It is definitely a bug.  In detail, the command installs a DAMOS scheme for monitoring purpose and retrieve the monitoring output from the scheme.  During installation, `damo` is mistakenly removing all monitored output in this case, specifically, dynamic virtual address ranges monitoring.  I will try to fix it soon, but it might take some time.

**Comment by honggyukim** [comment] 2023-06-06 13:27
Thanks for the confirmation. If `damo stat` doesn't work as expected then I might have to check if kernel module is better for my purpose.

I saw your live demo for printing WSS at https://youtu.be/-kx9AyiIar0?t=309, but the kernel API looks  different from now. I'm just wondering if there is an example kernel module code that uses damon APIs for reference.

**Comment by sj-aws** [comment] 2023-06-06 21:40
You may reference `mm/damon/reclaim.c` and `mm/damon/lru_sort.c` for example DAMON API usage from kernel module.

BTW, you may be able to work around the `damo stat` issue by installing the monitoring scheme you want to use to `damo start`, like below.

```
$ sudo ./damo start --damos_action stat --damos_access_rate 5% max "../masim/masim ../masim/configs/zigzag.cfg"
[...]
$ sudo ./damo stat regions --size_only --access_rate 5% max
kdamond 0 ctx 0
95.383 MiB
```

Note that a new interface for this feature will be implemented in future, and this `stat regions` command might be deprecated.

**Comment by honggyukim** [comment] 2023-06-07 08:56
> You may reference mm/damon/reclaim.c and mm/damon/lru_sort.c for example DAMON API usage from kernel module.

I initially thought the meaning of kernel module as dynamic kernel module that can be `insmod`ed at runtime, but it doesn't look like that.

I saw that there is no `EXPORT_SYMBOL` in the files under `mm/damon/*` now. Could you please confirm that the live demo with `insmod`able kernel module in the above youtube link is no longer available?

> BTW, you may be able to work around the damo stat issue by installing the monitoring scheme you want to use to damo start, like below.

Thanks. I saw that the output is printed as expected.

> Note that a new interface for this feature will be implemented in future, and this stat regions command might be deprecated.

I may have to keep that in mind so that I shouldn't too much rely on this interface. Thanks for your help again.

**Comment by sj-aws** [comment] 2023-06-07 17:14
> I saw that there is no EXPORT_SYMBOL in the files under mm/damon/* now. Could you please confirm that the live demo with insmodable kernel module in the above youtube link is no longer available?

You're correct, DAMON API is not supporting loadable modules at the moment.  I had to export some symbols for only the demo.  The exporting change has never been merged into the mainline.  Note that that was mainly because we don't have use case, not because we don't want to let loadable modules use DAMON API.

> I may have to keep that in mind so that I shouldn't too much rely on this interface.

Thank you.  I was aiming to make the new interface before v2.0.0, though the version number means nothing.  The estimated timeline was to demonstrate the new interface in OSSummit Europe if I could attend.  I will further prioritize this work.

**Comment by honggyukim** [comment] 2023-06-08 07:07
> You're correct, DAMON API is not supporting loadable modules at the moment. I had to export some symbols for only the demo.

Thanks for the confirmation. I was a bit confused :)

> Note that that was mainly because we don't have use case, not because we don't want to let loadable modules use DAMON API.

I will see if this can be a strong use case, but never mind for now.

> Thank you. I was aiming to make the new interface before v2.0.0, though the version number means nothing. The estimated timeline was to demonstrate the new interface in OSSummit Europe if I could attend. I will further prioritize this work.

Thank you for your help again. I will keep watching how it goes.

**Closed** 2023-07-01 20:08 UTC

**Comment by sj-aws** [comment] 2023-07-01 20:14
Fixed the issue with the commented commit.  With the commit, it works as expected, like below.

```
$ sudo ./damo start "../masim/masim ../masim/configs/stairs.cfg"
[...]
$ sudo ./damo stat regions --access_rate 5% max --size_only
kdamond 0 ctx 0
9.594 MiB
```

Note that `damo stat` is only experimental feature, and will be deprecated soon.  `damo show` will replace it, but it is also in the unstable development stage.

Please feel free to open this again.
